server:
  port: 8110
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
  application:
    name: guli-edu
  jackson:
   time-zone: GMT+8
   date-format: yyyy-MM-dd HH:mm:SS
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
