server:
  port: 8110
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
  redis:
    host: 182.61.56.79
    port: 6666
  application:
    name: guli-edu
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:SS
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    sentinel:
      transport:
        port: 8081 # 跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址
        clientIp: localhost  # 当前应用的ip
      eager: true #取消控制台懒加载，服务启动即可看到sentinel中对当前服务的监控
      filter:
        url-patterns: /** #默认拦截规则为 /*
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.atguigu.guli.service.edu.feign.OssFileService: debug #以什么级别监控哪个接口
ribbon:
  ConnectTimeout: 5000 #连接建立的超时时长，默认1秒
  ReadTimeout: 5000 #处理请求的超时时间，默认为1秒
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1
feign:
  sentinel:
    enabled: true